''''

"Cowboy guess-off"

Izveijdoja - Semijs Artūrs Ozols DP1-1

'''
from time import sleep
from os import system
import random

leaderboard = {}

def update_leaderboard(player, score): 
    if player in leaderboard:
        leaderboard[player] += score
    else:
        leaderboard[player] = score

def play_game():
    picked_number = random.randint(1, 100)
    print("Number has been picked. Guess a number between 1 and 100!")
    
    player1 = input("Player 1, enter your name: ")
    player2 = input("Player 2, enter your name: ")
    
    player1_guess = int(input(f"{player1}, enter your guess: "))
    player2_guess = int(input(f"{player2}, enter your guess: "))
    
    player1_diff = abs(picked_number - player1_guess)
    player2_diff = abs(picked_number - player2_guess)
    
    print(f"The picked number was: {picked_number}")
    print(f"{player1}'s guess: {player1_guess}")
    print(f"{player2}'s guess: {player2_guess}")
    
    if player1_diff < player2_diff:
        print("  O   __")
        print("--|--/")
        print("  |")
        print(" / \ ")
        print("/   \ ")
        sleep(0.3)
        system("cls")
        print("         _")
        sleep(0.3)
        system("cls")
        print("          _")
        sleep(0.3)
        system("cls")
        print("           _")
        sleep(0.3)
        system("cls")
        print("            _")
        sleep(0.3)
        system("cls")
        print("             _")
        sleep(0.3)
        system("cls")
        print("              _")
        sleep(0.3)
        system("cls")
        print("               _")
        sleep(0.3)
        system("cls")
        print("                _")
        sleep(0.3)
        system("cls")
        print("                 _")
        sleep(0.3)
        system("cls")
        print("                  _")
        sleep(0.3)
        system("cls")
        print("                   _")
        sleep(0.3)
        system("cls")
        print("                    _")
        sleep(0.3)
        system("cls")
        print("                     _")
        sleep(0.3)
        system("cls")
        print("                      _")
        sleep(0.3)
        system("cls")
        print("                       _")
        sleep(0.3)
        system("cls")
        print("                        _   __   O   ")
        print("                              \--|--")
        print("                                 |")
        print("                                / \ ")
        print("                               /   \ ")
        sleep(0.3)
        system("cls")
        print("                         _  __   O   ")
        print("                              \--|--")
        print("                                 |")
        print("                                / \ ")
        print("                               /   \ ")
        sleep(0.3)
        system("cls")
        print("                          _ __   O   ")
        print("                              \--|--")
        print("                                 |")
        print("                                / \ ")
        print("                               /   \ ")
        sleep(0.3)
        system("cls")
        print("                           ___   O   ")
        print("                              \--|--")
        print("                                 |")
        print("                                / \ ")
        print("                               /   \ ")
        sleep(0.3)
        system("cls")
        print("                            __   O    Oh no!   ")
        print("                              \--|--")
        print("                                 |")
        print("                                / \ ")
        print("                               /   \ ")
        sleep(0.5)
        system("cls")
        print("                            __      O   ")
        print("                                 \-   -   |- -")
        print("                                   |")  
        print("                                    / \ ")
        print("                                 /       \ ")
        print("KAAAAAABOOOOOMMM!!!!!!")
        sleep(0.5)
        system("cls")
        print("              <<Fin>>")
        sleep(1)
        system("cls")
        print(f"{player1} wins!")
        update_leaderboard(player1, 1)
    elif player2_diff < player1_diff:
        print("                            __   O   ")
        print("                              \--|--")
        print("                                 |")
        print("                                / \ ")
        print("                               /   \ ")
        sleep(0.3)
        system("cls")
        print("                          _")
        sleep(0.3)
        system("cls")
        print("                         _")
        sleep(0.3)
        system("cls")
        print("                        _")
        sleep(0.3)
        system("cls")
        print("                       _")
        sleep(0.3)
        system("cls")
        print("                      _")
        sleep(0.3)
        system("cls")
        print("                     _")
        sleep(0.3)
        system("cls")
        print("                    _")
        sleep(0.3)
        system("cls")
        print("                   _")
        sleep(0.3)
        system("cls")
        print("                  _")
        sleep(0.3)
        system("cls")
        print("                 _")
        sleep(0.3)
        system("cls")
        print("                _")
        sleep(0.3)
        system("cls")
        print("               _")
        sleep(0.3)
        system("cls")
        print("              _")
        sleep(0.3)
        system("cls")
        print("  O   __     _")
        print("--|--/")
        print("  |")
        print(" / \ ")
        print("/   \ ")
        sleep(0.3)
        system("cls")
        print("  O   __    _")
        print("--|--/")
        print("  |")
        print(" / \ ")
        print("/   \ ")
        sleep(0.3)
        system("cls")
        print("  O   __  _")
        print("--|--/")
        print("  |")
        print(" / \ ")
        print("/   \ ")
        sleep(0.3)
        system("cls")
        print("  O   ___")
        print("--|--/")
        print("  |")
        print(" / \ ")
        print("/   \ ")
        sleep(0.3)
        system("cls")
        print("  O   __ Oh no!")
        print("--|--/")
        print("  |")
        print(" / \ ")
        print("/   \ ")
        sleep(0.3)
        system("cls")
        print("   O    __")
        print("- - | -  -/")
        print("     |")
        print("   /    \ ")
        print("/     \ ")
        sleep(0.3)
        system("cls")
        print("            Fin")
        sleep(1)
        system("cls")
        print(f"{player2} wins!")
        update_leaderboard(player2, 1)
    else:
        print("It's a tie!")
        update_leaderboard(player1, 0.5)
        update_leaderboard(player2, 0.5)
    
    print("\nLeaderboard:")
    for player, score in leaderboard.items():
        print(f"{player}: {score} point(s)")
    
    play_again = input("Do you want to play again? (yes/no): ")
    if play_again.lower() == "yes":
        play_game()

play_game()
